version: '3'
services:
    mongo:
        image: mongo
        ports:
            - "27017"
    web:
        env_file: .env
        build: .
        command: bash -c "npm run dev"
        volumes:
            - .:/code
        ports:
            - "5000:5000"
        links:
            - mongo
